openapi: 3.0.0
info:
  title: JupyterHub API
  description: API for the Spawner UI of JupyterHub
  version: 0.1.0

paths:
  /test:
    post:
      operationId: api.hello_world
      responses:
        '200':
          description: OK

    